# -*- coding: utf-8 -*-
"""AppOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14TvnsN4XUpfMzXvp2fEz7kuAOJRz1a-l
"""

from google.colab.patches import cv2_imshow

!pip install pytesseract
!apt-get install tesseract-ocr-tha

!apt-get install tesseract-ocr-tha

!pip install langdetect

!pip install numpy

!pip install opencv-contrib-python

import matplotlib.pyplot as plt
import cv2
import pytesseract

import numpy as np

img = cv2.imread('/content/IMG_3483.JPG', cv2.IMREAD_COLOR)

plt.imshow(img)
plt.show()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

rotate_img = cv2.rotate(gray, cv2.cv2.ROTATE_90_COUNTERCLOCKWISE)
cv2_imshow(rotate_img)

print(rotate_img.shape)
rotate_resize = cv2.resize(rotate_img,(400,400))
cv2_imshow(rotate_resize)

text = pytesseract.image_to_string(rotate_resize, 'tha+eng')
print(text)

text = pytesseract.image_to_string(rotate_img, 'tha+eng')
print(text)